### PR TITLE
Making changes to match our coffeescript style

### PR DESCRIPTION
**Pull request by kirkchris**
from the main coffeescript style guidelines. let me know what you guys think!

### CODE REVIEW

**Comment by ajcantu** [comment]
do you think (long-term?) we should change any of our style guidelines to match the default ones? just curious.

**Comment by casey-sendbridge** [comment]
I can't wait to check the guidelines out when I have a moment.  It's powerful stuff I think.  Is there cyclomatic complexity limits in the default?  as maddening as that one is, I think it affects test coverage which is another item on our radar

**Comment by kirkchris** [comment]
re: @ajcantu , good question. There's only a few things we do differently which I think we could switch:

- optional use of commas
- optional use of {}
- optional use of () depending on readability (less interested in this)

Simon and I were just talking how we really don't like `and` over `&&` even though that is best practice, so I'd definitely argue against making that switch.

re: @casey-sendbridge cool! looking forward to your thoughts. There is nothing in the guidelines about it, but if you have ideas we should add them! Coffeelint also has some support for it as described here: http://www.coffeelint.org/ so if you are interested we could create a story to add it there and then test/fix some areas of our code that are failing it!

**Comment by kirkchris** [comment]
Going to merge this and then recreate our repo so we aren't always connected to the forked one.

**Pull request merged**
